### ISSUE TITLE
Possible race with concurrent pushes

### ISSUE THREAD

**Issue by blaizard** [RusPiRo/ruspiro-channel#7]
When 2 pushes append at the same time, there might be a race when setting the tail.

Here is the scenario:
If we first try to push on an empty queue, the first element will be the head, but imagine that another element is pushed at the same time. Then the tail might be set to the second element, leaving the first one not pop-able.

I think a potential fix is simple and would be to add an `else` condition to the `if` which implies that only the first element that is on the head can be also be the tail.
```
  /// Push a new element to the end of the [Queue]. The queue takes ownership of the value passed
  pub fn push(&self, value: T) {
    ...
    // 3. let the old node know it's next node.
    if !old_node.is_null() {
      unsafe {
        (*old_node).next.store(node, Ordering::SeqCst);
      }
    }
    else {
      // 4. if the tail is not yet pointing anywhere set the tail to the node just inserted
      dmb();
      // we can ignore the result of this operation. Err means the tail was alread set - so no need to update
      let _ = self
        .tail
        .compare_exchange(ptr::null_mut(), node, Ordering::AcqRel, Ordering::Relaxed);
      dsb();
    }
  }
```

**Comment by 2ndTaleStudio** [comment]
Hi,
thanks for filing this issue. I scratched my head a while thinking about this use case and when it could happen and indeed there is a rare chance of concurrent pushes to the queue that looses track of one of those pushes.

I think this could be solved by checking the result of updating the tail.
If this update fails because the tail != null_ptr the tail shall be checked against the nodes next value. If the tail == node.next than we can swap the tail with this node and the chain of nodes in the queue should be valid again and no node lost. I'll implement and test this approach. It might be quite hard to simulate though..
Let me know if you have any further suggestion.

Code:
```rust
// 4. if the tail is not yet pointing anywhere set the tail to the node just inserted
    unsafe {
      __dmb(SY);
    }
    if let Err(_) =
      self
        .tail
        .compare_exchange(ptr::null_mut(), node, Ordering::AcqRel, Ordering::Relaxed)
    {
      // the tail was not `null` while updating - so there might be a concurrent push to the queue is happening
      // if the current tail equals the current's node next value we have to swap the tail
      unsafe {
        __dmb(SY);
      }
      let next = unsafe { (*node).next.load(Ordering::SeqCst) };
      // now swap the tail to recreate the correct node chain and thus nothing get's lost
      let _ = self
        .tail
        .compare_exchange(next, node, Ordering::AcqRel, Ordering::Relaxed);
    }
    unsafe {
      __dsb(SY);
    }
```

Dry-Run through the code states assuming the queue is used on two cores of the raspberry pi concurrently thus a concurrent
push could happen:

Step | Action | Core 0 | Core 1
-----|--------|--------|---------
1 | PUSH | head= null, tail = null, create node0 | head = null, tail = null, create node1
2.0 | Update HEAD (atomic on core0) | head = node1, tail = null, old_node = null | head = node1, tail = null
2.1 | Update HEAD (atomic on core1) | head = node2, tail = null, old_node = null | head = node2, tail = null, old_node = node1
3, | Update old_node.next | head = node2, tail = null, old_node = null | head = node2, tail = null, node1.next = node2
4.0 | Update TAIL (atomic on core0) | head = node2, tail = node1, node1.next = node2 | head = node2, tail = node1, node1.next = node2
4.1 | Update TAIL (atomic on core1) | no state change | no state change

After this the queue is fine tail=node1 -> next = node2 -> head ==> all items could be popped.
However, the issue you have identified happens if the processing order of step 3 and 4 for each core is not the same - in this case a dangling node could appear.
So how does this change with the proposed change if we switch the order of 4.0 and 4.1

Step | Action | Core 0 | Core 1
-----|--------|--------|---------
4.1 | Update TAIL (atomic on core1) | head = node2, tail = node2, node1.next = node2 | head = node2, tail = node2, node1.next = node2
4.0 | Update TAIL (atomic on core0) | head = node2, tail = node2 == node1.next => tail = node1 | head = node2, tail = node1, node1.next = node2

==> this now recreates the correct node chain ...
